name: build
on: [push, pull_request]
jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install dependencies
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j3
