name: build
on: [push, pull_request]
jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install dependencies
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install boost
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j1

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install dependencies
      run: sudo apt-get install libboost-all-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j1
